version: '3.8'

networks:
  gatewaynet:
  usernet:
  lognet:

services:
  api-gateway:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - "8007:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gatewaynet
    depends_on:
      - user-service-api
      - log-service-api

  userdb-host:
    container_name: userdb-host
    build:
      context: ./User_Management_service
      dockerfile: Dockerfile.user.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    networks:
      - usernet
    ports:
      - 8001:1433

  logdb-host:
    container_name: logdb-host
    build:
      context: ./Log_Management_service
      dockerfile: Dockerfile.log.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    networks:
      - lognet
    ports:
      - 8002:1433

  user-service-api:
    container_name: user-service-api
    image: user-service-api
    build:
      context: ./User_Management_service
      dockerfile: Dockerfile.userserver
    networks:
      - gatewaynet
      - usernet
    environment: 
      - DB_HOST=userdb-host
      - USER_DB_NAME=userdb
      - DB_SA_PASSWORD=Password123
    depends_on:
      - userdb-host
    
  log-service-api:
    container_name: log-service-api
    image: log-service-api
    build:
      context: ./Log_Management_service
      dockerfile: Dockerfile.logserver
    networks:
      - gatewaynet
      - lognet
    environment: 
      - DB_HOST=logdb-host
      - LOG_DB_NAME=logdb
      - DB_SA_PASSWORD=Password123
    depends_on:
      - logdb-host
