version: '3.8'

networks:
  backend:

services:
  userdb-host:
    container_name: userdb-host
    build:
      context: ./User_Management_service
      dockerfile: Dockerfile.user.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    networks:
      - backend
    ports:
      - 8001:1433

  logdb-host:
    container_name: logdb-host
    build:
      context: ./Log_Management_service
      dockerfile: Dockerfile.log.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    networks:
      - backend
    ports:
      - 8002:1433

  user-service-api:
    container_name: user-service-api
    image: user-service-api
    build:
      context: ./User_Management_service
      dockerfile: Dockerfile.userserver
    networks:
      - backend
    ports:
      - 8003:8080
    environment: 
      - DB_HOST=userdb-host
      - USER_DB_NAME=userdb
      - DB_SA_PASSWORD=Password123
    depends_on:
      - track-and-count-service-api
      - userdb-host
    
  log-service-api:
    container_name: log-service-api
    image: log-service-api
    build:
      context: ./Log_Management_service
      dockerfile: Dockerfile.logserver
    networks:
      - backend
    ports:
      - 8004:8080
    environment: 
      - DB_HOST=logdb-host
      - LOG_DB_NAME=logdb
      - DB_SA_PASSWORD=Password123
    depends_on:
      - track-and-count-service-api
      - logdb-host

  model-service-api:
    container_name: model-service-api
    image: model-service-api
    build:
      context: ./Model_Management_service
      dockerfile: Dockerfile.modelserver
    networks:
      - backend
    ports:
      - 8005:8080
    depends_on:
      - track-and-count-service-api

  track-and-count-service-api:
    container_name: track-and-count-service-api
    image: track-and-count-service-api
    build:
      context: ./Track_and_Count_System
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 8006:8006
